# Configuration for the OMR subproject

# This file will enable the GC and it's dependencies (port / thread)
# as well as a set of experimental GC APIs.

# Required OMR Components

set(OMR_PORT   ON CACHE INTERNAL "")
set(OMR_THREAD ON CACHE INTERNAL "")
set(OMR_GC     ON CACHE INTERNAL "")

# Enable experimental GC APIs

set(OMR_GC_EXPERIMENTAL_CONTEXT        ON CACHE INTERNAL "")
set(OMR_GC_EXPERIMENTAL_OBJECT_SCANNER ON CACHE INTERNAL "")
set(OMR_GC_EXPERIMENTAL_ALLOCATOR      ON CACHE INTERNAL "")

# Disable the scavenger and heap compaction
# Note: If you're following through the workshop, you will eventually be flipping these flags to "ON"

set(OMR_GC_MODRON_SCAVENGER  OFF CACHE INTERNAL "")
set(OMR_GC_MODRON_COMPACTION OFF CACHE INTERNAL "")

# Default-on options

set(OMR_GC_THREAD_LOCAL_HEAP ON CACHE INTERNAL "")
set(OMR_NOTIFY_POLICY_CONTROL ON CACHE INTERNAL "")
set(OMR_THR_CUSTOM_SPIN_OPTIONS ON CACHE INTERNAL "")
set(OMR_THR_SPIN_CODE_REFACTOR ON CACHE INTERNAL "")
set(OMR_THR_SPIN_WAKE_CONTROL ON CACHE INTERNAL "")
set(OMR_THR_THREE_TIER_LOCKING ON CACHE INTERNAL "")

# Unfortunately

set(OMR_WARNINGS_AS_ERRORS OFF CACHE INTERNAL "")

# Disable unrelated OMR elements

set(OMR_EXAMPLE OFF CACHE INTERNAL "")
set(OMR_FVTEST OFF CACHE INTERNAL "")
set(OMR_JIT  OFF CACHE INTERNAL "")
set(OMR_JITBUILDER OFF CACHE INTERNAL "")
set(OMR_OM OFF CACHE INTERNAL "")
set(OMR_DDR OFF CACHE INTERNAL "")
set(OMR_OMRSIG OFF CACHE INTERNAL "")
set(OMR_TEST_COMPILER OFF CACHE INTERNAL "")
set(OMR_THR_FORK_SUPPORT OFF CACHE INTERNAL "")
